# To be used by `dune` where the relative path
# to ocaml-interop is different and we don't
# want to be inside the toplevel workspace.

[package]
name = "callable_rust"
version = "0.1.0"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml-interop = { path = "../../../../.." }

[workspace]
