[package]
name = "rust-caller"
version = "0.1.0"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
ocaml-interop = { path = "../.." }

[build-dependencies]
cc = "1"
ocaml-interop-dune-builder = { path = "../../dune-builder" }