[package]
name = "rust-caller"
version = "0.1.0"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
edition = "2021"

[dependencies]
ocaml-interop = { path = "../.." }
ocaml-sys = "*"

[dev-dependencies]
once_cell = "*"
