[package]
name = "rust-caller"
version = "0.1.0"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
edition = "2018"

[dependencies.ocaml-interop]
path = "../.."

[dependencies.ocaml-interop-runtime]
path = "../../runtime"

[dev-dependencies]
serial_test = "*"