[package]
name = "inspect-runtime-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ocaml-interop = { path = "../../.." }
ocaml-interop-inspect = { path = "../.." }

[build-dependencies]
cc = "1"
ocaml-interop-dune-builder = { path = "../../../dune-builder" }
