# To be used by `dune` where the relative path
# to ocaml-interop is different and we don't
# want to be inside the toplevel workspace.

[package]
name = "noalloc_primitives_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
# Path relative to _build/default/docs/examples/noalloc_primitives/rust/
ocaml-interop = { path = "../../../../../../" }

[workspace]
