# To be used by `dune` where the relative path
# to ocaml-interop is different and we don't
# want to be inside the toplevel workspace.

[package]
name = "records_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml-interop = { path = "../../../../../../" } # Path relative to _build/default/docs/examples/records/rust/

[workspace]
